name: Python Lint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.10.1
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.1
    - name: Lint with pycodestyle
      run: |
        pip install pycodestyle
        pycodestyle --max-line-length 100 ./app
    - name: Lint app with flake
      run: |
        pip install flake8
        flake8 --max-line-length 100 app
    - name: Lint app with black
      run: |
        pip install black
        black --line-length 100 app